# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pull request against these branches will trigger this build
pr: 
  - main

# no CI trigger
trigger: none

jobs:
- job: Component_governance
  timeoutInMinutes: 20 # how long to run the job before automatically cancelling
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'
      failOnAlert: true
